# Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел
чисел от 12 до 24 невключительно
2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах
метода reshape число -1.
3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах
метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для
строк).
4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой
из нормального распределения со средним, равным 0 и среднеквадратичным отклонением,
равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и
исходный массив.
6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с
интервалом 2.
7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1
невключительно с интервалом 2. В чем разница между массивами a и b?
8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого
больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.
9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy),
состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и
почему?
10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных
равномерно распределенных целых чисел от 0 до 16 невключительно.
© geekbrains.ru
212. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D,
поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.
13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции
numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве
источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых
соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему
элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы
D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [1]:
import numpy as np
import pandas as pd

### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
a.shape

(12,)

### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [4]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [7]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [8]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [9]:
a1 = a.reshape(-1, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
a2 = a.reshape(-1, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a3 = a.reshape(12, -1)
a3

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [12]:
a4 = a.reshape(6, -1)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
a5 = a.reshape(4, -1)
a5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [14]:
a = np.arange(12)
b = a.reshape(1, 12)

In [37]:
a.ndim

1

In [38]:
b.ndim

2

## Ответ: нельзя , т.к. размерность равна 2

### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [21]:
normal = np.random.default_rng().normal(0, 1, 12).reshape(3, 4)
normal

array([[-0.25064999,  1.08679842,  0.63962067, -1.94188887],
       [ 0.86178571,  2.06386231, -1.80421702, -0.30973114],
       [ 0.64227533, -2.65279857, -0.80991114,  1.61412242]])

In [160]:
normal.size

12

In [163]:
normal1 = normal.flatten()
normal1

array([-0.25064999,  1.08679842,  0.63962067, -1.94188887,  0.86178571,
        2.06386231, -1.80421702, -0.30973114,  0.64227533, -2.65279857,
       -0.80991114,  1.61412242])

In [164]:
normal1.size

12

In [165]:
normal1.ndim

1

### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [25]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [27]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [34]:
a.ndim

1

In [35]:
b.ndim

2

## Ответ: Массивы имеют разные размерности

### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

Пусть m - кол-во строк, n - кол-во столбцов, тогда по условию:

n*m + (n + 1)*m = 10, при n > 1 и n принадлежит Z

Очевидно, что данное уравнение имеет целочисленное решение только при n = 2, следовательно m = 2

In [108]:
n, m = 2, 2

In [166]:
a = np.zeros((n, m), dtype='int')
b = np.ones((n + 1, m), dtype='int')

In [167]:
a

array([[0, 0],
       [0, 0]])

In [168]:
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [169]:
result = np.concatenate((a, b), axis=0)
result

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1]])

In [170]:
result.size

10

### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [113]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [120]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [121]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [123]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [125]:
B.shape

(4, 4)

In [126]:
det_B = np.linalg.det(B)
det_B

0.0

## Ответ: Обратную матрицу вычислить не получится, т.к. B - сингулярная (определитель равен 0)

In [127]:
# B_inv = np.linalg.inv(B)

### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [128]:
np.random.seed(42)

### 11.Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.


In [130]:
c = np.random.default_rng().integers(low=0, high=16, size=16)
c

array([ 4,  7, 15,  9,  5,  3,  4, 13, 11,  0,  5,  2,  9,  0, 11, 10])

### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [172]:
C = c.reshape(4, 4)
C

array([[ 4,  7, 15,  9],
       [ 5,  3,  4, 13],
       [11,  0,  5,  2],
       [ 9,  0, 11, 10]])

In [173]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [174]:
C = C * 10
D = np.add(B, C)
D

array([[ 45,  84, 173, 122],
       [ 64,  80, 126, 252],
       [133,  86, 199, 232],
       [122, 122, 322, 402]])

In [175]:
det_D = np.linalg.det(D)
det_D

-95170799.99999994

In [176]:
rank = np.linalg.matrix_rank(D)
rank

4

In [177]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.00519151, -0.00234484,  0.01617051, -0.0062868 ],
       [ 0.01935993,  0.01945912,  0.00141241, -0.01888878],
       [ 0.00175306, -0.0118944 , -0.00259449,  0.00842149],
       [-0.00570406,  0.00433347, -0.00325793,  0.00338234]])

### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [179]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 0., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.]])

In [180]:
# убедимся что нет других значений кроме 0 и 1
test = D_inv[(D_inv != 0) & (D_inv != 1)]
test.size

0

In [181]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [182]:
C

array([[ 40,  70, 150,  90],
       [ 50,  30,  40, 130],
       [110,   0,  50,  20],
       [ 90,   0, 110, 100]])

In [183]:
E = np.where(D_inv, B, C)
E

array([[ 40,  70,  23,  90],
       [ 14,  50,  86, 130],
       [ 23,   0,  50, 212],
       [ 90, 122, 110, 302]])